header:
  version: 11

distro: poky
target: core-image-minimal

repos:
  poky:
    url: https://git.yoctoproject.org/git/poky
    branch: scarthgap
    commit: 6b7474f7ca29076d28df81a49feec6311fa18202
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:
